#!/usr/bin/env node
/**
 * Build script: reads content/ directory and generates src/generated-data.js
 * for server/runtime consumption.
 */

const fs = require('fs');
const path = require('path');

// Simple frontmatter parser (no dependencies needed)
function parseFrontmatter(raw) {
  const match = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) throw new Error('Invalid frontmatter');
  
  const meta = {};
  let currentKey = null;
  let inArray = false;
  
  for (const line of match[1].split('\n')) {
    const kvMatch = line.match(/^(\w+):\s*(.*)$/);
    if (kvMatch) {
      const [, key, val] = kvMatch;
      if (val === '') {
        // Could be start of array or empty value
        meta[key] = [];
        currentKey = key;
        inArray = true;
      } else {
        // Remove surrounding quotes
        meta[key] = val.replace(/^["']|["']$/g, '');
        currentKey = key;
        inArray = false;
      }
    } else if (inArray && currentKey) {
      const arrMatch = line.match(/^\s+-\s+(.+)$/);
      if (arrMatch) {
        meta[currentKey].push(arrMatch[1].replace(/^["']|["']$/g, ''));
      }
    }
  }
  
  const content = match[2].trim();
  return { meta, content };
}

function readEntries(dir) {
  if (!fs.existsSync(dir)) return [];
  
  return fs.readdirSync(dir)
    .filter(f => f.endsWith('.md'))
    .map(f => {
      const raw = fs.readFileSync(path.join(dir, f), 'utf-8');
      const { meta, content } = parseFrontmatter(raw);
      return {
        slug: meta.slug,
        date: meta.date,
        title: meta.title,
        tags: Array.isArray(meta.tags) ? meta.tags : [meta.tags].filter(Boolean),
        content,
      };
    })
    .sort((a, b) => b.date.localeCompare(a.date)); // newest first
}

// Read config
const config = JSON.parse(fs.readFileSync(path.join(__dirname, 'content', 'config.json'), 'utf-8'));

// Read strategy
let strategy = {};
try {
  strategy = JSON.parse(fs.readFileSync(path.join(__dirname, 'content', 'strategy.json'), 'utf-8'));
} catch (e) {
  console.log('No strategy.json found, skipping...');
}

// Read entries
const entries = readEntries(path.join(__dirname, 'content', 'entries'));
const learnEntries = readEntries(path.join(__dirname, 'content', 'learn'));

// Generate JS module
// Use JSON.stringify for safe embedding (handles backticks, quotes, newlines)
const output = `// AUTO-GENERATED by build.js — DO NOT EDIT
// Generated at: ${new Date().toISOString()}

export const SITE_CONFIG = ${JSON.stringify(config.siteConfig, null, 2)};

export const STATS = ${JSON.stringify(config.stats, null, 2)};

export const VERIFICATION = ${JSON.stringify(config.verification, null, 2)};

export const STRATEGY = ${JSON.stringify(strategy, null, 2)};

export const ENTRIES = ${JSON.stringify(entries, null, 2)};

export const LEARN_ENTRIES = ${JSON.stringify(learnEntries, null, 2)};
`;

const outPath = path.join(__dirname, 'src', 'generated-data.js');
fs.writeFileSync(outPath, output, 'utf-8');

const jsonOutput = {
  SITE_CONFIG: config.siteConfig,
  STATS: config.stats,
  VERIFICATION: config.verification,
  STRATEGY: strategy,
  ENTRIES: entries,
  LEARN_ENTRIES: learnEntries
};

const frontendPublicDir = path.join(__dirname, 'frontend', 'public');
if (fs.existsSync(frontendPublicDir)) {
  const jsonOutPath = path.join(frontendPublicDir, 'generated-data.json');
  fs.writeFileSync(jsonOutPath, JSON.stringify(jsonOutput, null, 2), 'utf-8');
  console.log(`✅ Generated ${jsonOutPath}`);
}

console.log(`✅ Generated ${outPath}`);
console.log(`   ${entries.length} entries, ${learnEntries.length} learn entries`);
if (Object.keys(strategy).length > 0) {
  console.log(`   Strategy: ${strategy.strategy?.name || 'loaded'}`);
}
